config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show, :index, :edit, :update , :create]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :books do
    resources :post_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
  end

  root 'home#top'
  get 'home/about' => 'home#about'
  get 'search' => 'searches#search'
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  validates :user_id, {presence: true}
  validates :book_id, {presence: true}
  belongs_to :book
  belongs_to :user
  validates_uniqueness_of :book_id, scope: :user_id
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :book_params


  def create
    # book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # redirect_back(fallback_location: root_path)
  end

  def destroy
    # book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_back(fallback_location: root_path)
    # redirect_to book_path(book)
  end

  def book_params
    @book = Book.find(params[:book_id])
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book.favorites.count, book_favorite_path(book), method: :delete, remote: true, class: "glyphicon glyphicon-heart" %>
<% else %>
  <%= link_to book.favorites.count, book_favorite_path(book), method: :post, remote: true, class: "glyphicon glyphicon-heart-empty" %>
<% end %>

app/views/favorites/create.js.erb
$("#book_<%= @book.id %> .favorite-btn").html("<%= j(render 'favorites/favorite', book: @book) %>");

app/views/favorites/destroy.js.erb
$("#book_<%= @book.id %> .favorite-btn").html("<%= j(render 'favorites/favorite', book: @book) %>");

app/views/favorites/show_follow.html.erb
<div class="col-md-12">
  <h3><%= @title %></h3>
    <% if @users.any? %>
    <table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name %></td>
					<td>フォロー数：<%= user.following.count %></td>
					<td>フォロワー数：<%= user.followers.count %></td>
					<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
    <% end %>
  </div>