config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:show, :index, :edit, :update , :create]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :books do
    resources :post_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
  end

  root 'home#top'
  get 'home/about' => 'home#about'
  get 'search' => 'searches#search'
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :post_comments, dependent: :destroy
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

def self.search(search, word)
  if search == "forward_match"
    @book = Book.where("title LIKE?","#{word}%")
  elsif search == "backward_match"
    @book = Book.where("title LIKE?","%#{word}")
  elsif search == "perfect_match"
    @book = Book.where("title LIKE?","#{word}")
  elsif search == "partial_match"
    @book = Book.where("title LIKE?","%#{word}%")
  else
    @book = Book.all
  end
end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def show
    @book = Book.find(params[:id])
    @post_comment = PostComment.new
    @book_new = Book.new
  end

  def index
    @books = Book.all
    @book = Book.new

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def delete
    @book = Book.find(params[:id])
    @book.destoy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    book = Book.find(params[:id])
    if current_user.id != book.user_id
    redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
	<% if @book.errors.any? %>
		<div id="error_explanation">
			<h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>


		<h1>Editing Book</h1>

		<%= render "books/newform", book: @book %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>
	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
	<% if @book.errors.any? %>
		<div id="error_explanation">
			<h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr id="book_<%= book.id %>">
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td class="favorite-btn"><%= render partial: "favorites/favorite", locals: { book: book} %></td>
					<td class="comments-count">コメント数：<%= book.post_comments.count %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>

app/views/books/show.html.erb
	<% if @book.errors.any? %>
		<div id="error_explanation">
			<h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>


<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book_new %>

	</div>
	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr id="book_<%= @book.id %>">
					<td>
						<%= link_to user_path(@book.user) do %>
							<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
							<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, book_path(@book) %></td>
					<td><%= @book.body %></td>
					<% if @book.user == current_user %>
					<td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
					<td class="favorite-btn"><%= render partial: "favorites/favorite", locals: { book: @book} %></td>
					<td class="comments-count">コメント数：<%= @book.post_comments.count %></td>
				</tr>
		</table>

		<div id="post_comments">
		<table>
			<%= render "post_comments/comment_area", book: @book %>
		</table>
		</div>

		<div class="post_comment">
			<%= form_with(model:[@book, @post_comment]) do |f| %>
				<div class="field row">
				<%= f.text_area :comment, class: "col-xs-9" %>
				<%= f.submit "送信" %>
				</div>
			<% end %>
		</div>
	</div>
</div>